basic_settings:
  site_title: Cali Eco Verde Smoke Supply
  favicon_image: /images/favicon.ico
  og_image:
  logo_image: /images/caliecosmoke-logo-white.png

# header:
#   header_image: /images/leaf.png
#   header_image_opacity: 0.2

colors:
  color1: '#49ac7f'
  color2: '#53b761'
  color3: '#d5f6f2'
  color4: '#daede5'
  text-color: '#202b2f'


phone: '4843345963'
scheduling_link: 'https://calendly.com/'

contact_settings:
  email: ecoverdesmokesupply@gmail.com
  email_subject: 'Message via Cali Eco Smoke Supply Website'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/'
  twitter_url: 'https://www.twitter.com/'
  instagram_url: 'https://www.instagram.com/'
  youtube_url: 'https://www.youtube.com/'
  pinterest_url: 'https://www.pinterest.com/'
  linkedin_url: 'https://www.linkedin.com/'
