basic_settings:
  site_title: Cali Eco Verde Smoke Supply
  favicon_image: /images/favicon.ico
  og_image:
  logo_image: /images/caliecosmoke-logo-white.png

colors:
  color1: '#49ac7f'
  color2: '#53b761'
  color3: '#d5f6f2'
  color4: '#daede5'
  text-color: '#292c30'

email: ecoverdesmokesupply@gmail.com
phone: 4843345963

contact_settings:
  form_action: 'https://formspree.io/ecoverdesmokesupply@gmail.com'
  confirmation_url: '/thanks'
  email_subject: 'Message via Cali Eco Smoke Supply Website'
  send_button_text: 'Send Message'
